spring:
  profiles:
    active: yit

---
spring: 
  profiles: yit
  thymeleaf: 
    cache: false
    mode: LEGACYHTML5 #去掉Thymeleaf强制校验，搭配nekohtml使用
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    
  datasource: 
    url: jdbc:mysql://rm-bp102k9m31w3854p4o.mysql.rds.aliyuncs.com:3306/pqdt_test?rewriteBatchedStatements=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&serverTimezone=CTT
    username: datacenter
    password: mimabutigong
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 100
    initialSize: 10
    minIdle: 1

server: 
  port: 9898
      
mybatis: 
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gk.model
  
---
spring:
  profiles: home
  thymeleaf: 
    cache: false
    mode: LEGACYHTML5 #去掉Thymeleaf强制校验，搭配nekohtml使用
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    
  datasource: 
    url: jdbc:mysql://localhost:3306/my_test?useSSL=false&rewriteBatchedStatements=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&serverTimezone=CTT
    username: root
    password: gkadmin
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql8如此配置
    filters: stat
    maxActive: 100
    initialSize: 10
    minIdle: 1

server: 
  port: 9898
      
mybatis: 
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gk.model
