server:
  port: 9898
  
spring: 
  thymeleaf: 
    cache: false
#    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    
  datasource: 
    url: jdbc:mysql://rm-bp102k9m31w3854p4o.mysql.rds.aliyuncs.com:3306/pqdt?rewriteBatchedStatements=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&serverTimezone=CTT
    username: datacenter
    password: yx7qSzIsq_sqwk
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 100
    initialSize: 10
    minIdle: 1
    
mybatis: 
  mapper-locations: classpath:/com/gk/mapper/*.xml
  type-aliases-package: com.gk.model